CREATE TABLE `delivery_requests` (
	`id` int AUTO_INCREMENT NOT NULL,
	`clientId` int NOT NULL,
	`createdBy` int,
	`deliveryDate` timestamp NOT NULL,
	`timeWindow` enum('morning','afternoon','custom') NOT NULL DEFAULT 'morning',
	`customTimeWindow` varchar(128),
	`siteName` varchar(256) NOT NULL,
	`addressStreet` varchar(256) NOT NULL,
	`addressCity` varchar(128) NOT NULL,
	`addressState` varchar(8) NOT NULL DEFAULT 'TX',
	`addressZip` varchar(16) NOT NULL,
	`estimatedMiles` int NOT NULL DEFAULT 0,
	`packageCount` int NOT NULL DEFAULT 0,
	`largeItemCount` int NOT NULL DEFAULT 0,
	`palletCount` int NOT NULL DEFAULT 0,
	`looseDeviceCount` int NOT NULL DEFAULT 0,
	`specialInstructions` text,
	`disclaimerAccepted` boolean NOT NULL DEFAULT false,
	`tripCents` int NOT NULL DEFAULT 0,
	`packageCents` int NOT NULL DEFAULT 0,
	`largeItemCents` int NOT NULL DEFAULT 0,
	`palletCents` int NOT NULL DEFAULT 0,
	`deviceCents` int NOT NULL DEFAULT 0,
	`totalCents` int NOT NULL DEFAULT 0,
	`trackingNumber` varchar(32),
	`status` enum('pending_payment','paid','scheduled','in_transit','delivered','failed','cancelled') NOT NULL DEFAULT 'pending_payment',
	`stripeCheckoutSessionId` varchar(256),
	`paidAt` timestamp,
	`receiverFirstName` varchar(128),
	`receiverLastName` varchar(128),
	`receiverPhone` varchar(32),
	`receiverEmail` varchar(256),
	`deliveredAt` timestamp,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `delivery_requests_id` PRIMARY KEY(`id`),
	CONSTRAINT `delivery_requests_trackingNumber_unique` UNIQUE(`trackingNumber`)
);
--> statement-breakpoint
