export const ENV = {
  appId: process.env.VITE_APP_ID ?? "",
  cookieSecret: process.env.JWT_SECRET ?? "",
  databaseUrl: process.env.DATABASE_URL ?? "",
  oAuthServerUrl: process.env.OAUTH_SERVER_URL ?? "",
  ownerOpenId: process.env.OWNER_OPEN_ID ?? "",
  isProduction: process.env.NODE_ENV === "production",
  forgeApiUrl: process.env.BUILT_IN_FORGE_API_URL ?? "",
  forgeApiKey: process.env.BUILT_IN_FORGE_API_KEY ?? "",
  resendApiKey: process.env.RESEND_API_KEY ?? "",
  resendFromEmail: process.env.RESEND_FROM_EMAIL ?? "",
  portalUrl: process.env.PORTAL_URL ?? "https://www.layeronestaging.com",
  supportEmail: process.env.SUPPORT_EMAIL ?? "info@layeronestaging.com",
  supportPhone: process.env.SUPPORT_PHONE ?? "+1 (469) 537-4378",
  ownerNotifyEmail: process.env.OWNER_NOTIFY_EMAIL ?? "info@layeronestaging.com",
};
